### ISSUE TITLE
[Bug]: VSCode V1.86.0 (possibly) broken

### ISSUE THREAD

**Issue by Rotaugenkiller2** [illixion/vscode-vibrancy-continued#129] opened 2024-02-07 14:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current Behavior:

No Opacity change (values from 0 - 1 including -1)
Screen flickering
- With "Prevent Flash" Enabled | Disabled
- With Refresh Interval ranging from 1 - 10000

https://github.com/illixion/vscode-vibrancy-continued/assets/159271456/27a5a112-54b3-4a5f-b580-212d99280664

### Expected Behavior

Expected Behavior:

Frosted Glass Transparent Visuals as seen in Screenshots

![download](https://github.com/illixion/vscode-vibrancy-continued/assets/159271456/abb96f02-192f-4aa6-89aa-100b4154eab3)
![59575968-56340c80-90db-11e9-8f52-5487e0e8c4f8](https://github.com/illixion/vscode-vibrancy-continued/assets/159271456/c619b835-cab8-40bf-bfbe-abc98e1dc214)

### Steps To Reproduce

1 - Launch VSCode as Administrator
2 - Install Vibrancy Continued and the Extension shown after installing Vibrancy Continued
3 - Press ctrl+shift+p or F1 and select "Reload Vibrancy"
4 - Reload & Restart VSCode

### Environment

```markdown
- OS: Windows 11 Pro (v 10.0.22621 Build 22621)
- VSCode: v 1.86.0
- Extension: Vibrancy Continued
- Theme: Dark+
```

### Anything else?

Tested on different System and still produced same Result. Most likely not caused by own System but by newest Update in January

**Comment by illixion** [comment] 2024-02-07 14:43
Duplicate of https://github.com/illixion/vscode-vibrancy-continued/issues/122

**Closed by illixion** 2024-02-07 14:43 UTC
Labels: bug, triage
