### ISSUE TITLE
[Bug]: Not working in vscode 1.82.0

### ISSUE THREAD

**Issue by JotaRata** [illixion/vscode-vibrancy-continued#95] opened 2023-09-09 06:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A error message pops up when Enabling Vibrancy through the command palette:

![imagen](https://github.com/illixion/vscode-vibrancy-continued/assets/36273501/035bf807-d1e4-40ad-8009-d305aae37f06)

### Environment

```markdown
- OS: Windows 11 22H2
- VSCode: 1.82.0
- Theme: Dark Modern
```

**Comment by illixion** [comment] 2023-09-09 11:40
Issue caused by Microsoft removing the setting for enabling HTML window controls in https://github.com/microsoft/vscode/pull/188793, unfortunately this means that the controls will no longer be transparent with the rest of the window on Windows platforms. Not sure how to proceed with that yet, but I'll fix the error during Vibrancy activation, so the extension will at least still work.

**Comment by illixion** [comment] 2023-09-09 12:00
Version 1.1.21 released with a fix, issue with opaque window controls that this causes will be tracked in #49.

**Closed by illixion** 2023-09-09 12:00 UTC
Labels: bug, triage
