### ISSUE TITLE
Line selection over multiple lines does add extra selected columns

### ISSUE THREAD

**Issue by AlexTemirbulatow** [illixion/vscode-vibrancy-continued#105] opened 2023-11-04 00:16 UTC
When selecting multiple lines of code, there will be added extra selected columns/blocks left and right on some lines.
Also, while selection multiple lines, there is added an extra selected column after the current cursor position.
It's not actually selected, just optical.

![extraHighlightedColumns](https://github.com/illixion/vscode-vibrancy-continued/assets/73587467/c0e566cc-a0b8-4637-b1bc-94e3f878bb4b)

**Comment by illixion** [comment] 2023-11-04 21:26
Duplicate of #76

**Closed by illixion** 2023-11-04 21:26 UTC
