### ISSUE TITLE
System control buttons background is black

### ISSUE THREAD

**Issue by BarryAllenJr** [illixion/vscode-vibrancy-continued#16] opened 2022-09-06 11:17 UTC
System control buttons don't get the acrylic effect. The rest of the title bar does.

this is what it looks like with  `"titleBar.activeBackground": "#2c2c2cc9"` (greyish color)
![image](https://user-images.githubusercontent.com/13165863/188621803-457c9cee-3935-4311-add8-e8179b125444.png)
and this is what it looks like with `"titleBar.activeBackground": "#2c2c2cc900"` (100% transparent)
![image](https://user-images.githubusercontent.com/13165863/188622441-9dceba00-d282-4cde-a424-5e79e8595f0e.png)

**Comment by illixion** [comment] 2022-09-06 12:35
Duplicate of #12, but thanks for letting me know about titleBar.activeBackground, I'll see if I can apply transparency where this parameter is used.

**Closed by illixion** 2022-09-06 12:35 UTC
