### ISSUE TITLE
[Bug]: Window of VSCode cannot be maximize after activing this effect

### ISSUE THREAD

**Issue by GFCYqw** [illixion/vscode-vibrancy-continued#151] opened 2024-05-18 19:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After active the effect, the window cann0t be **maximize**.
But resize, minimize and close still working.
And after >Disable Vibrancy< the bug disappers.

### Expected Behavior

Maxmize window.

### Steps To Reproduce

1. Downlod this plugin.(This step won't make bug occur)
2. Active it in settings.
3. The window of VSCode cannt be maximize.
4. >Disable Vibrancy< then bug disappers.

### Environment

```markdown
- OS: Windows 11, version 23H2
- VSCode: 1.89.1
- Extension: Vibrancy Continued
- Theme: Default dark theme
```

**Comment by illixion** [comment] 2024-05-19 10:26
Duplicate of https://github.com/illixion/vscode-vibrancy-continued/issues/140

**Closed by illixion** 2024-05-19 10:26 UTC
Labels: bug, triage
